🐛 fix : 리뷰 저장 시, 이미지리스트 null 에러 해결 (#14)
#13 에서 createReview로 합치면서 해결된 줄 알았으나 여전히 해결안됐음

[에러]
java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because the return value of "com.server.springStudy.domain.entity.Review.getReviewImageList()" is null

Review 엔티티의 reviewImageList 필드 초기화 안함 -> null로 초기화되어 있음

[해결]
ReviewConverter.toReview에서 Review 엔티티 생성할 때 reviewImageList 초기화해줘야 함 **